### PR TITLE
Gigaset N870 enhancements

### PR DESCRIPTION
**Pull request by BnLG**
Hello,

This PR brings enhancements for Gigaset N870 devices.

It's a whole copy of `N870-83.v2.39.0` plugin, with following differences :
- fix a bug with `sip_subscribe_mwi` handling preventing provd from building the template
- fix of the `_UA_REGEX` for devices with old firmware (for ex 2.39) which get their new firmware sending their UA between plain double quotes...
- update to last 2.48 firmware version (basic functions tested, working)
- allow mobile devices firmware update
- small cosmetic update on display name, to mimic other Gigaset devices, such as Gigaset N720
- proper SIP TLS / SRTP handling

Unfortunately though, I've encountered a bug between N870 and Asterisk using SIP TLS, where calls are terminated as soon as they're put on hold (which is rather annoying).
I've then disabled SIP TLS support for now, I'll document bug report here for ref, and I'll bring an update of the plugin once solved.

Thank you 👍

### CODE REVIEW

**Comment by BnLG** [comment]
@bloom1 it's ready to be merged, no more update for now 😉
Thank you 👍

**Review by bloom1 — CHANGES_REQUESTED** [review]
Great work @BnLG !!

Could you please update the copyright dates in the files?
Also, if you want a new plugin to be built, you must add a section in the `plugins/build.py` file. If you look at what [Zuul built](https://zuul.wazo.community/logs/47/147/9c9538389a58cbb6d07c830e70d7b60250ac9cb9/check/wazo-provd-plugins/4893a8b/plugins/) you can see that the new plugin is not in the list.
You can copy this part: https://github.com/wazo-platform/wazo-provd-plugins/blob/master/plugins/wazo-gigaset/build.py#L29:L32
Then change the name of the function and the plugin.

Thank you!

**Comment by BnLG** [comment]
Many thanks for your review @bloom1, and for your guidelines 👍 
Plugin now added to the list :)

**Comment by bloom1** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Comment by bloom1** [comment]
> 

I doubt this breaks anything :smile: if it does you would have seen it with your testing. Gigaset are not known to break features when upgrading.

**Comment by BnLG** [comment]
Many thanks again @bloom1 for your review.
I tested the Zuul build today, and did not encounter any issue.

Btw, what's the best practice ?
Making a new plugin for every new firmware version ?
Or keep a single plugin, updating firmware for it ?

Here I've made an additional plugin, as for Snom & Yealink.

Thank you 👍

**Comment by bloom1** [comment]
> Many thanks again @bloom1 for your review. I tested the Zuul build today, and did not encounter any issue.
> 
> Btw, what's the best practice ? Making a new plugin for every new firmware version ? Or keep a single plugin, updating firmware for it ?
> 
> Here I've made an additional plugin, as for Snom & Yealink.
> 
> Thank you +1

It depends on how/when the plugin was made. I prefer a different plugin for each version, but sometimes a brand was made so that there is a plugin for each model.

**Pull request merged**
