### PR TITLE
intercom for digium

### PR DESCRIPTION
**Pull request by tikismoke**
This and another patch in wazo plugin allow a digium d70 to work as intercom

### CODE REVIEW

**Comment by tikismoke** [comment]
see this one
https://github.com/wazo-pbx/xivo-config/pull/1

**Comment by bloom1** [comment]
Hi tikismoke,

I created a plugin for the new firmware, it is on the testing repo (url: http://provd.wazo.community/plugins/1/testing/). It is named `wazo-digium-2.8.1`. Could you try it on your phone and tell me if it works?

Thanks!

**Comment by tikismoke** [comment]
i'll check this WeekEnd as i'll be alone @home so it will be easier to test.

All i have to do is to replace the digium provd from testing directly from Wazo web interface right (changing to testing)?

i'll let you know

**Comment by bloom1** [comment]
Hi Tikismoke

You have to change the URL in the web interface. The procedure is here:
http://documentation.wazo.community/en/stable/administration/provisioning/basic_configuration.html#alternative-plugins-repository
Also, I recommend you change the plugin used by the device afterwards. It's in the `Services ‣ IPBX ‣ Device` section. If you don't do this, the device will never use the newer plugin. Also make sure to download the firmware in the plugin settings.

I tried it here on a D70 but I want to make sure it works on yours as well.

Thanks!

**Comment by tikismoke** [comment]
Are you sure of it's name?
I can't find the wazo-digium-2.8.1in testing or anywhere else :(

**Comment by bloom1** [comment]
Oh, indeed the testing repo has been overriden while testing another phone. You can go back to it now and it should be there. Sorry!

**Comment by tikismoke** [comment]
I'll try it in a few hours.

No problem. I also received 2 tb30 but it's a nightmare to make them work

**Comment by tikismoke** [comment]
It works,
It has update firmware when changing "greffon" in device, Grab it's conf, and can answer to intercom.

Just a problem in my conf it was doing a "bip" just before auto answering. Is it possible to re-add it and allow to remove it from intercom conf part in wazo. With this new plugin, it do not change neither i check or not this option.

ps: Crap i re(changed to the old one and it do no more make bipbip :(

**Comment by bloom1** [comment]
Hi,

Can you try to put <Intercom> (first letter uppercase) instead of <answer> in the Dialplan? I have not tried this and I do not have the phone right now. You could also try <intercom> (all lowercase)

Thanks!

**Comment by tikismoke** [comment]
Do not work more. Does this bip before answer say you something when you try on your side? Or is it only in my head (could be a istaje as the aastra do this too, meaning make a sound before auto-answer)

**Comment by tikismoke** [comment]
Ok seems to be my fault....

In fact i was using this in my digium MAC.cfg file:
`<alert Alert-Info="Intercom" ringtone_id="Beep" ring_type="ring-answer" />`

ring-answer in ring_type differs from only answer as it made the phone ring first one time.
Like this it ring's one time and then auto-answer, maybe it's this difference that might be use with the intercom wazo tab option called like this in 'fr' : 

> Silence, ne pas jouer le bip:

For now all is ok and might be adapt by everyone that look's for this option.

**Comment by bloom1** [comment]
Hi Tikismoke, 

Nice! At least you were able to make it work like you wanted. However I'm pretty sure I do not have this option available as a template variable. The `Silence, ne pas jouer le bip` option is an option passed by a dialplan variable. Can you try using `ring-answer` with your Beep ringtone, but enabling the `Silence, ne pas jouer le bip` option and tell me if it beeps? If it does not beep that might be the right way to do it.

Thanks!

**Comment by tikismoke** [comment]
Ok after some more test on it...
in the digium mac config file you should change answer by ring answer if you want to have the music played once like says here:
https://wiki.asterisk.org/wiki/display/DIGIUM/Ringing+Types+and+Intercom

> One Ring followed by automated Answer - ring-answer

So the Silence, ne pas jouer le bip  option should interact directly with the provisionning file changing the way the intercom part is interpret by the phone from answer to ring-answer or vice versa:(

It can be merged like that and add a spec in doc no? instead of now it tells it's not working.

**Comment by tikismoke** [comment]
ps: by the way i' trying to do the same with TB30 from thomson for my kids, but i can't make intercom work at all. (provisionning is ok with file already download from asterisk france forum)

**Comment by bloom1** [comment]
Superseded by https://github.com/wazo-platform/wazo-provd-plugins/pull/103

**Pull request closed without merging**
