### PR TITLE
Snom FW 10.1.39.11 and introduce D717

### PR DESCRIPTION
**Pull request by ymolinet**
Tested on D735 et D715.
Introduce D717 but not fully tested.

### CODE REVIEW

**Comment by ymolinet** [comment]
Tested also on D375

**Comment by ymolinet** [comment]
I'm also adding support of Grandstream GXP2130 (tested)
Ringtone from grandstream are available.
Language pack is also available, but not install in the proper way (seems it necessary to rename the correct file as language.txt)

**Comment by bloom1** [comment]
Hi @ymolinet !

Thanks for your PR. However, please create another PR for Grandstream.

Thank you!

**Comment by ymolinet** [comment]
Rebuild and update in #27

**Pull request closed without merging**
