### PR TITLE
Zuul migration

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
@sduthil a bit randomly, do you have an opinion on this ?

**Comment by sduthil** [comment]
That's OK for me :) Ready to switch it over to the new Zuul instance?

On second look, I don't understand why we need a VM for this job, a container should be enough. But that change can wait.

**Review by sduthil — APPROVED** [review]

**Comment by rgarrigue** [comment]
@sduthil I tried the container way, there was a hard blocker. I didn't saved the log and SF was reseted meanwhile, but basicaly

> synchronize task can't happens on k1s

You can open a PR changing the nodeset to see what's happening

**Pull request merged**
