### PR TITLE
Grandstream GXP21XX V2

### PR DESCRIPTION
**Pull request by technophreak**
Grandstream GXP2130, GXP2135, GXP2140, GXP2160 and GXP2170 in version 1.0.11.85

### CODE REVIEW

**Comment by fouille** [comment]
hello @technophreak 
please see : https://github.com/wazo-platform/wazo-provd-plugins/pull/259

**Comment by technophreak** [comment]
Could anyone help me figure out why I am still getting a 404 when trying to provision ?

The proper template is created locally but wazo-provd keeps giving me a 404.


```
root@CLBVX-WAZO-01:~# cat /var/lib/wazo-provd/plugins/wazo-grandstream-1.0.11.85/var/tftpboot/Grandstream/cfg000b82865e6a.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gs_provision version="1">
 <config version="2">
    <item name="users.admin.password">REDACTED</item>
    <item name="dateTime.ntp.server.1">184.107.62.100</item>
    <item name="language.gui">en</item>
    
 . . .
 
```

```
root@CLBVX-WAZO-01:~# curl -A "Grandstream Model HW GXP2170 SW 1.0.11.85 DevId 000b82865e6a" localhost:8667/cfg000b82865e6a.xml

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>File not found.</p>
  </body>
</html>
```

**Comment by sboily** [comment]
Hello, check the wazo-provd logs to give us more information.

**Comment by technophreak** [comment]
> Hello, check the wazo-provd logs to give us more information.

It's basically the same 404 i see in nginx logs
```
2024-07-04 12:24:48,846 [249296] (INFO) (wazo_provd.devices.ident): Processing HTTP request: b'/cfg000b82865e6a.xml'
2024-07-04 12:24:48,849 [249296] (INFO) (wazo_provd.devices.ident): <14> Extracted device info: {'vendor': 'Grandstream', 'model': 'GXP2170', 'version': '1.0.11.85', 'mac': '00:0b:82:86:5e:6a', 'ip': '127.0.0.1'}
2024-07-04 12:24:48,850 [249296] (INFO) (wazo_provd.devices.ident): <14> Retrieved device id: 2ec2767ee7824444b3e0b3176d4ea545
2024-07-04 12:24:48,852 [249296] (INFO) (wazo_provd.devices.ident): <14> Routing request to plugin wazo-grandstream-1.0.11.85
2024-07-04 12:24:48,853 [249296] (INFO) (twisted): 127.0.0.1 - - [04/Jul/2024:16:24:48 +0000] "GET /cfg000b82865e6a.xml HTTP/1.0" 404 145 "-" "Grandstream Model HW GXP2170 SW 1.0.11.85 DevId 000b82865e6a"
```

I have the same issue with official plugin grandstream_1_0_8_6

```
2024-07-04 12:19:17,676 [249296] (INFO) (wazo_provd.devices.ident): Processing HTTP request: b'/cfg000000002200.xml'
2024-07-04 12:19:17,681 [249296] (INFO) (wazo_provd.devices.ident): <12> Extracted device info: {'vendor': 'Grandstream', 'model': 'GXP2120', 'version': '1.0.8.6', 'mac': '00:00:00:00:22:00', 'ip': '127.0.0.1'}
2024-07-04 12:19:17,682 [249296] (INFO) (wazo_provd.devices.ident): <12> Retrieved device id: cb4496cea4d143bdaebdb051e1c7d1ef
2024-07-04 12:19:17,683 [249296] (INFO) (wazo_provd.devices.ident): <12> Routing request to plugin wazo-grandstream-1.0.8.6
2024-07-04 12:19:17,694 [249296] (INFO) (twisted): 127.0.0.1 - - [04/Jul/2024:16:19:16 +0000] "GET /cfg000000002200.xml HTTP/1.0" 404 145 "-" "Grandstream Model HW GXP2120 SW 1.0.8.6 DevId 000000002200"

**Comment by bloom1** [comment]
HI @technophreak 
Thank you for the PR.

Indeed the files are generated in the Grandstream directory. It's to better differentiate the requests coming into provd.
I'll rebase and merge.
Thanks a lot!

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
