### PR TITLE
fix error template funckeys Aastra 6865i

### PR DESCRIPTION
**Pull request by fouille**

### CODE REVIEW

**Comment by bloom1** [comment]
I need to grab a 6865i at the office to test

**Comment by pc-m** [comment]
> I need to grab a 6865i at the office to test

I've rebased the branch. Do you happen to have a 6865i at home? Otherwise I'll go get one next week.

**Comment by bloom1** [comment]
> > I need to grab a 6865i at the office to test
> 
> I've rebased the branch. Do you happen to have a 6865i at home? Otherwise I'll go get one next week.

No :frowning_face:

**Comment by pc-m** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
