### PR TITLE
Gigaset, add support for N670 IP PRO

### PR DESCRIPTION
**Pull request by BnLG**
Hi,

Let's add support for the new Gigaset `N670 IP PRO` (and also for the Gigaset `N870E IP PRO`), which shares exactly the same configuration as the already existing `N870 IP PRO`.
Let's then create a `Nx70 IP PRO` plugin (which is how Gigaset names them).

First commit is then a 1:1 copy of `N870-83.v2.48.0` plugin.

Next commits are modifications, explained below.
It add support for `N670 IP PRO` and  `N870E IP PRO`.
It updates firmware to [last `83.v2.49.1` version](https://teamwork.gigaset.com/gigawiki/pages/viewpage.action?pageId=1350862266).
It enables SIP TLS (kept disabled in #147), which now properly works (`SipProvider.0.UseSIPS` must be set to `0`, after support from Gigaset team).
It properly sets `ToneScheme` according to configured locale.
It deregisters accounts for detached handsets (`WithDeregOnHsNotReachable`), which makes more sense than the contrary.
Finally, it renames the keys to the ones [defined in the README](https://github.com/wazo-platform/wazo-provd-plugins#plugin-information-files).

Thank you 👍

_Note that this is a rework of #159, after the move to Python3._

### CODE REVIEW

**Comment by BnLG** [comment]
Hi @bloom1, this PR is ready for review, it follows #159, properly reworking it, after the move to Python3.
Many thanks 👍

**Comment by BnLG** [comment]
Hi @bloom1, thank you for your review.
Cisco files were an issue with my git client, good catch, corrected !
I'm not sure why linters does not like `common.py` though 😕

**Comment by bloom1** [comment]
@BnLG you can run `tox -e black` in the repo root to reformat the code (this will run black with the configuration we specified in `tox.ini`)

**Comment by BnLG** [comment]
Many thanks @bloom1, let me see if I can run this on macOS :)

**Comment by bloom1** [comment]
> Many thanks @bloom1, let me see if I can run this on macOS :)

Given that both tox and black are written in Python I have no doubt that it is possible to use them on macOS :wink:

**Comment by BnLG** [comment]
Did the trick, many thanks @bloom1 👍

**Review by bloom1 — APPROVED** [review]

**Comment by bloom1** [comment]
recheck

**Comment by BnLG** [comment]
Many thanks guys 👍

**Pull request merged**
