### PR TITLE
WAZO-1760: provd behind reverse proxy

### PR DESCRIPTION
**Pull request by bloom1**

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Review by pc-m — APPROVED** [review]
Is there a mechanism to prevent older provd from using the new plugins?

**Comment by pc-m** [comment]
> Is there a mechanism to prevent older provd from using the new plugins?

I looked at the code and answered the question myself. Default values are used if the configuration keys do not exists

**Comment by bloom1** [comment]
@pc-m yes I'm doing that right now :smile:

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
@sduthil do you have an idea on how to fix the RETRY_LIMIT above?

**Comment by sduthil** [comment]
> @sduthil do you have an idea on how to fix the RETRY_LIMIT above?

I'd recommend changing Zuul / Python versions in another PR and rebase this one over it, there are too many changes here to debug this properly.

**Comment by bloom1** [comment]
@pc-m is that still good with you?

**Review by pc-m — APPROVED** [review]

**Pull request merged**
