### PR TITLE
Add mypy and basic typing

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Comment by sopelj** [comment]
The linters is failing, not because there is an error in the code, but because it is unable to install Twisted in the pipeline. It seems it needs to be compiled and gcc is missing from the docker image.

**Review by bloom1 — DISMISSED** [review]
Rebasing, something is off

**Review by bloom1 — DISMISSED** [review]
LGTM :heart_eyes:

**Comment by bloom1** [comment]
@ahogui12 do I have to merge the Zuul-related changes before they can be applied to another branch?

**Comment by ahogui12** [comment]
I think it should be correct for the "zuul-only" jobs. But the failing one is a tox job, and checking in the logs, the `pre-run.yaml` is never ran so it does not install `gcc` as wanted

**Comment by fblackburn1** [comment]
@bloom1 I let you merge and/or update this PR. I only fix the zuul part

**Review by bloom1 — APPROVED** [review]
Thank you @fblackburn1 for the Zuul fix :smiley:

**Pull request merged**
